# Stage 1 - the build process
FROM node:lts-alpine as build
COPY . .
RUN yarn && yarn build

# Stage 2 - the serve process
FROM node:lts-alpine
ENV PORT 8080
ENV NODE_ENV production
COPY --from=build dist dist
COPY --from=build package.json .
RUN yarn install --pure-lockfile --prod
CMD node dist/server
EXPOSE ${PORT}
